import { useState, type FormEvent } from 'react';
import { ArrowRight, BookOpenCheck, FlaskConical, LockKeyhole, Mail } from 'lucide-react';
import { hasApi } from '../../model/api';

interface Props { enterDemo: () => void; signIn: (email: string, password: string) => Promise<void>; loading: boolean; error: string; }

export default function AccessPage({ enterDemo, signIn, loading, error }: Props) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  function submit(event: FormEvent) { event.preventDefault(); void signIn(email, password); }
  return <div className="access-page"><section className="access-hero"><div className="access-brand"><span className="brand-mark"><FlaskConical size={25}/></span><span>LAB<span>MAT</span></span></div><div className="access-hero-content"><span className="eyebrow light">LABORATORIO DE APRENDIZAJE</span><h1>Las matemáticas se entienden <em>resolviendo.</em></h1><p>Explora conceptos, calcula paso a paso y transforma cada ejercicio en aprendizaje.</p><div className="access-highlights"><span><BookOpenCheck size={19}/> Cuatro áreas de estudio</span><span><FlaskConical size={19}/> Procedimientos claros</span></div></div><div className="access-pattern" aria-hidden="true">∑<span>ƒ(x)</span></div></section><section className="access-form-area"><div className="access-card"><div className="access-card-icon"><FlaskConical size={27}/></div><span className="eyebrow">BIENVENIDO</span><h2>Comienza a explorar</h2><p className="muted">Accede al laboratorio y trabaja con herramientas interactivas.</p>{hasApi && <form onSubmit={submit} className="access-form"><label>Correo electrónico<div className="input-icon"><Mail size={19}/><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="tu@correo.com" autoComplete="email" required/></div></label><label>Contraseña<div className="input-icon"><LockKeyhole size={19}/><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tu contraseña" autoComplete="current-password" required/></div></label>{error && <p className="error-message" role="alert">{error}</p>}<button className="button button-primary full" disabled={loading}>{loading ? 'Ingresando…' : 'Iniciar sesión'}<ArrowRight size={18}/></button></form>}{hasApi && <div className="separator"><span>o</span></div>}<button className={`button ${hasApi ? 'button-outline' : 'button-primary'} full`} onClick={enterDemo}>Entrar en modo demostración<ArrowRight size={18}/></button><p className="access-disclaimer">Los cálculos y el historial de demostración se ejecutan en este navegador. No se guardan en la base de datos.</p></div></section></div>;
}
