import { useState, type FormEvent } from 'react';
import { ArrowRight, Info } from 'lucide-react';
import { useCalculationController } from '../../controller/useCalculationController';
import { calculateStatistics, type StatisticsInput, type StatisticsMethod } from '../../model/statistics';
import { NumberField } from '../components/Fields';
import ResultPanel from '../components/ResultPanel';

const names: Record<StatisticsMethod, string> = { descriptiva: 'Estadística descriptiva', binomial: 'Distribución binomial', poisson: 'Distribución de Poisson', normal: 'Distribución normal' };

export default function StatisticsView() {
  const [input, setInput] = useState<StatisticsInput>({ method: 'descriptiva', data: '4, 6, 8, 8, 10, 12, 12, 12, 14', n: 10, k: 3, p: 0.4, lambda: 4, mean: 100, deviation: 15, x: 115 });
  const controller = useCalculationController('estadistica', calculateStatistics);
  const update = <K extends keyof StatisticsInput>(key: K, value: StatisticsInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent) { event.preventDefault(); controller.run(names[input.method], input); }
  return <div className="workspace-grid"><section className="form-card"><div className="form-card-head"><span className="form-head-icon">04</span><div><h2>Analiza datos</h2><p>Calcula medidas y probabilidades con explicación.</p></div></div><form onSubmit={submit} className="fields"><label className="field"><span>Herramienta</span><select value={input.method} onChange={(event) => { update('method', event.target.value as StatisticsMethod); controller.reset(); }}>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{input.method === 'descriptiva' && <label className="field"><span>Conjunto de datos</span><textarea rows={5} value={input.data} onChange={(event) => update('data', event.target.value)} placeholder="4, 6, 8, 8, 10"/><small>Separa los números con comas, espacios o punto y coma.</small></label>}{input.method === 'binomial' && <><div className="field-row"><NumberField label="Ensayos n" value={input.n} onChange={(value) => update('n', value)} step="1" min={0}/><NumberField label="Éxitos k" value={input.k} onChange={(value) => update('k', value)} step="1" min={0}/></div><NumberField label="Probabilidad de éxito p" value={input.p} onChange={(value) => update('p', value)} min={0} max={1} hint="Un número entre 0 y 1."/></>}{input.method === 'poisson' && <div className="field-row"><NumberField label="Media λ" value={input.lambda} onChange={(value) => update('lambda', value)} min={0}/><NumberField label="Eventos k" value={input.k} onChange={(value) => update('k', value)} step="1" min={0}/></div>}{input.method === 'normal' && <><div className="field-row"><NumberField label="Media μ" value={input.mean} onChange={(value) => update('mean', value)}/><NumberField label="Desviación σ" value={input.deviation} onChange={(value) => update('deviation', value)} min={0}/></div><NumberField label="Valor x para P(X ≤ x)" value={input.x} onChange={(value) => update('x', value)}/></>}<button className="button button-primary">Calcular <ArrowRight size={18}/></button></form><div className="form-tip"><Info size={17}/><span>En estadística descriptiva se usa varianza poblacional.</span></div></section><ResultPanel result={controller.result} error={controller.error} reset={controller.reset}/></div>;
}
