import { Link } from 'react-router-dom';
import { ArrowRight, BrainCircuit, Calculator, ChartNoAxesCombined, ChevronRight, Clock3, Lightbulb, Sigma, Sparkles } from 'lucide-react';
import { getHistory } from '../../model/history';
import InstitutionalWatermark from '../components/InstitutionalWatermark';

const modules = [
  { id: 'logica', label: 'Lógica matemática', description: 'Tablas de verdad y simplificación de expresiones booleanas.', icon: BrainCircuit, color: 'indigo', tools: 'Tablas de verdad · Álgebra booleana' },
  { id: 'finanzas', label: 'Matemáticas financieras', description: 'Interés, descuentos y tablas de amortización explicadas.', icon: Calculator, color: 'amber', tools: 'Interés · Descuentos · Amortización' },
  { id: 'computacionales', label: 'Mat. computacionales', description: 'Raíces, interpolación y ecuaciones diferenciales.', icon: Sigma, color: 'teal', tools: 'Raíces · Interpolación · EDO' },
  { id: 'estadistica', label: 'Probabilidad y estadística', description: 'Medidas descriptivas y distribuciones de probabilidad.', icon: ChartNoAxesCombined, color: 'rose', tools: 'Datos · Binomial · Poisson · Normal' },
];

export default function DashboardPage() {
  const recent = getHistory().slice(0, 3);
  return <><section className="welcome-banner"><div className="welcome-copy"><span className="eyebrow light">TU ESPACIO DE APRENDIZAJE</span><h1>Aprende matemáticas<br/><em>paso a paso.</em></h1><p>Elige un módulo, resuelve ejercicios y comprende cada resultado con su procedimiento.</p><Link to="/laboratorio/logica" className="button button-gold">Explorar módulos <ArrowRight size={18}/></Link></div><InstitutionalWatermark variant="dashboard"/><div className="welcome-graphic" aria-hidden="true"><div className="graphic-ring ring-one"/><div className="graphic-ring ring-two"/><span className="formula-one">ƒ(x) = x² + 2x</span><span className="formula-two">∑ nᵢ / N</span><span className="formula-three">P(A ∧ B)</span></div></section><div className="section-header"><div><span className="eyebrow">EXPLORA Y PRACTICA</span><h2>Áreas de estudio</h2></div><span className="section-caption">4 módulos disponibles</span></div><div className="module-grid">{modules.map(({ id, label, description, icon: Icon, color, tools }) => <Link className={`module-card ${color}`} key={id} to={`/laboratorio/${id}`}><div className="module-icon"><Icon size={27} strokeWidth={1.8}/></div><h3>{label}</h3><p>{description}</p><div className="module-tools">{tools}</div><span className="module-action">Abrir laboratorio <ChevronRight size={18}/></span></Link>)}</div><div className="dashboard-bottom"><section className="dashboard-panel"><div className="panel-heading"><div><Clock3 size={20}/><h3>Actividad reciente</h3></div><Link to="/historial" className="text-button">Ver historial <ArrowRight size={16}/></Link></div>{recent.length ? <ul className="recent-list">{recent.map((entry) => <li key={entry.id}><span className="recent-dot"/><div><strong>{entry.method}</strong><small>{new Date(entry.createdAt).toLocaleString('es-MX')}</small></div><span>{entry.result.value}</span></li>)}</ul> : <div className="panel-empty">Aún no hay cálculos. Tu actividad de demostración aparecerá aquí.</div>}</section><section className="tip-panel"><div className="tip-icon"><Lightbulb size={23}/></div><span className="eyebrow">CONSEJO DE ESTUDIO</span><h3>Entiende el proceso, no solo la respuesta</h3><p>Cada herramienta desglosa las fórmulas y muestra los pasos para que puedas comprobar tu trabajo.</p><Link to="/asistente">Sobre el asistente <ArrowRight size={16}/></Link><Sparkles className="tip-sparkle" size={66}/></section></div></>;
}
